package crypto

/*
Hasher defines the interface for a password hasher. Each hasher is a different
implementation of a hashing algorithm (e.g., bcrypt, argon2, etc.).
*/
type Hasher interface {

	/*
		Name returns the name of the hashing algorithm used by this hasher.
	*/
	Name() string

	/*
		Hash generates a hash for the given password string.
	*/
	Hash(password string) (string, error)

	/*
		IsValidHash checks if the provided hash is a valid hash generated by this
		hasher.
	*/
	IsValidHash(hash string) bool

	/*
		Compare checks if the provided hash matches the hash of the password string.
	*/
	Compare(hash, password string) (bool, error)

	/*
		CompareParameters checks if the parameters of the provided hash match
		the current hashing parameters. This is used for determining if a hash
		needs to be rehashed due to changes in hashing parameters.
	*/
	CompareParameters(hash string) (bool, error)
}
